// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mlagents_envs/communicator_objects/command.proto

#include "mlagents_envs/communicator_objects/command.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace communicator_objects {
}  // namespace communicator_objects
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto = nullptr;
const ::uint32_t TableStruct_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n0mlagents_envs/communicator_objects/com"
    "mand.proto\022\024communicator_objects*-\n\014Comm"
    "andProto\022\010\n\004STEP\020\000\022\t\n\005RESET\020\001\022\010\n\004QUIT\020\002b"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto = {
    false,
    false,
    127,
    descriptor_table_protodef_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto,
    "mlagents_envs/communicator_objects/command.proto",
    &descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto,
    file_level_service_descriptors_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto_getter() {
  return &descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto(&descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto);
namespace communicator_objects {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CommandProto_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto);
  return file_level_enum_descriptors_mlagents_5fenvs_2fcommunicator_5fobjects_2fcommand_2eproto[0];
}
bool CommandProto_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace communicator_objects
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
