repos:

- repo: https://github.com/python/black
  rev: 22.3.0
  hooks:
  - id: black
    exclude: >
        (?x)^(
            .*_pb2.py|
            .*_pb2.pyi|
            .*_pb2_grpc.py
        )$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    name: mypy-ue-agents
    files: "ue-agents/.*"
    args: [--ignore-missing-imports, --disallow-incomplete-defs, --no-strict-optional]
    additional_dependencies: [types-PyYAML, types-attrs, types-protobuf, types-setuptools, types-filelock]
  - id: mypy
    name: mypy-ue-agents-envs
    files: "ue-agents-envs/.*"
    # Exclude protobuf files and don't follow them when imported
    exclude: ".*_pb2.py"
    args: [--ignore-missing-imports, --disallow-incomplete-defs, --no-strict-optional, --follow-imports, skip]
    additional_dependencies: [types-PyYAML, types-attrs, types-protobuf, types-setuptools, types-filelock]

- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: >
        (?x)^(
            .*_pb2.py|
            .*_pb2_grpc.py
        )$

    additional_dependencies: [flake8-comprehensions==3.2.2, flake8-tidy-imports==4.1.0, flake8-bugbear==20.1.4]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    name: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
  - id: clang-format
    args: [-i]
    files: \.(c|cc|cpp|cs|h|hpp)$
