// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ueagents_envs/communicator_objects/agent_info_action_pair.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ueagents_5fenvs_2fcommunicator_5fobjects_2fagent_5finfo_5faction_5fpair_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ueagents_5fenvs_2fcommunicator_5fobjects_2fagent_5finfo_5faction_5fpair_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ueagents_envs/communicator_objects/agent_info.pb.h"
#include "ueagents_envs/communicator_objects/agent_action.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ueagents_5fenvs_2fcommunicator_5fobjects_2fagent_5finfo_5faction_5fpair_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2fagent_5finfo_5faction_5fpair_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2fagent_5finfo_5faction_5fpair_2eproto;
namespace communicator_objects {
class AgentInfoActionPairProto;
struct AgentInfoActionPairProtoDefaultTypeInternal;
extern AgentInfoActionPairProtoDefaultTypeInternal _AgentInfoActionPairProto_default_instance_;
}  // namespace communicator_objects
PROTOBUF_NAMESPACE_OPEN
template <>
::communicator_objects::AgentInfoActionPairProto* Arena::CreateMaybeMessage<::communicator_objects::AgentInfoActionPairProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace communicator_objects {

// ===================================================================


// -------------------------------------------------------------------

class AgentInfoActionPairProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:communicator_objects.AgentInfoActionPairProto) */ {
 public:
  inline AgentInfoActionPairProto() : AgentInfoActionPairProto(nullptr) {}
  ~AgentInfoActionPairProto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AgentInfoActionPairProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgentInfoActionPairProto(const AgentInfoActionPairProto& from);
  AgentInfoActionPairProto(AgentInfoActionPairProto&& from) noexcept
    : AgentInfoActionPairProto() {
    *this = ::std::move(from);
  }

  inline AgentInfoActionPairProto& operator=(const AgentInfoActionPairProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgentInfoActionPairProto& operator=(AgentInfoActionPairProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgentInfoActionPairProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgentInfoActionPairProto* internal_default_instance() {
    return reinterpret_cast<const AgentInfoActionPairProto*>(
               &_AgentInfoActionPairProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AgentInfoActionPairProto& a, AgentInfoActionPairProto& b) {
    a.Swap(&b);
  }
  inline void Swap(AgentInfoActionPairProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgentInfoActionPairProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgentInfoActionPairProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgentInfoActionPairProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgentInfoActionPairProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AgentInfoActionPairProto& from) {
    AgentInfoActionPairProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgentInfoActionPairProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "communicator_objects.AgentInfoActionPairProto";
  }
  protected:
  explicit AgentInfoActionPairProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAgentInfoFieldNumber = 1,
    kActionInfoFieldNumber = 2,
  };
  // .communicator_objects.AgentInfoProto agent_info = 1;
  bool has_agent_info() const;
  void clear_agent_info() ;
  const ::communicator_objects::AgentInfoProto& agent_info() const;
  PROTOBUF_NODISCARD ::communicator_objects::AgentInfoProto* release_agent_info();
  ::communicator_objects::AgentInfoProto* mutable_agent_info();
  void set_allocated_agent_info(::communicator_objects::AgentInfoProto* agent_info);
  private:
  const ::communicator_objects::AgentInfoProto& _internal_agent_info() const;
  ::communicator_objects::AgentInfoProto* _internal_mutable_agent_info();
  public:
  void unsafe_arena_set_allocated_agent_info(
      ::communicator_objects::AgentInfoProto* agent_info);
  ::communicator_objects::AgentInfoProto* unsafe_arena_release_agent_info();
  // .communicator_objects.AgentActionProto action_info = 2;
  bool has_action_info() const;
  void clear_action_info() ;
  const ::communicator_objects::AgentActionProto& action_info() const;
  PROTOBUF_NODISCARD ::communicator_objects::AgentActionProto* release_action_info();
  ::communicator_objects::AgentActionProto* mutable_action_info();
  void set_allocated_action_info(::communicator_objects::AgentActionProto* action_info);
  private:
  const ::communicator_objects::AgentActionProto& _internal_action_info() const;
  ::communicator_objects::AgentActionProto* _internal_mutable_action_info();
  public:
  void unsafe_arena_set_allocated_action_info(
      ::communicator_objects::AgentActionProto* action_info);
  ::communicator_objects::AgentActionProto* unsafe_arena_release_action_info();
  // @@protoc_insertion_point(class_scope:communicator_objects.AgentInfoActionPairProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::communicator_objects::AgentInfoProto* agent_info_;
    ::communicator_objects::AgentActionProto* action_info_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2fagent_5finfo_5faction_5fpair_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AgentInfoActionPairProto

// .communicator_objects.AgentInfoProto agent_info = 1;
inline bool AgentInfoActionPairProto::has_agent_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.agent_info_ != nullptr);
  return value;
}
inline const ::communicator_objects::AgentInfoProto& AgentInfoActionPairProto::_internal_agent_info() const {
  const ::communicator_objects::AgentInfoProto* p = _impl_.agent_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::communicator_objects::AgentInfoProto&>(
      ::communicator_objects::_AgentInfoProto_default_instance_);
}
inline const ::communicator_objects::AgentInfoProto& AgentInfoActionPairProto::agent_info() const {
  // @@protoc_insertion_point(field_get:communicator_objects.AgentInfoActionPairProto.agent_info)
  return _internal_agent_info();
}
inline void AgentInfoActionPairProto::unsafe_arena_set_allocated_agent_info(
    ::communicator_objects::AgentInfoProto* agent_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_info_);
  }
  _impl_.agent_info_ = agent_info;
  if (agent_info) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:communicator_objects.AgentInfoActionPairProto.agent_info)
}
inline ::communicator_objects::AgentInfoProto* AgentInfoActionPairProto::release_agent_info() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::communicator_objects::AgentInfoProto* temp = _impl_.agent_info_;
  _impl_.agent_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::communicator_objects::AgentInfoProto* AgentInfoActionPairProto::unsafe_arena_release_agent_info() {
  // @@protoc_insertion_point(field_release:communicator_objects.AgentInfoActionPairProto.agent_info)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::communicator_objects::AgentInfoProto* temp = _impl_.agent_info_;
  _impl_.agent_info_ = nullptr;
  return temp;
}
inline ::communicator_objects::AgentInfoProto* AgentInfoActionPairProto::_internal_mutable_agent_info() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.agent_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::communicator_objects::AgentInfoProto>(GetArenaForAllocation());
    _impl_.agent_info_ = p;
  }
  return _impl_.agent_info_;
}
inline ::communicator_objects::AgentInfoProto* AgentInfoActionPairProto::mutable_agent_info() {
  ::communicator_objects::AgentInfoProto* _msg = _internal_mutable_agent_info();
  // @@protoc_insertion_point(field_mutable:communicator_objects.AgentInfoActionPairProto.agent_info)
  return _msg;
}
inline void AgentInfoActionPairProto::set_allocated_agent_info(::communicator_objects::AgentInfoProto* agent_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.agent_info_);
  }
  if (agent_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(agent_info));
    if (message_arena != submessage_arena) {
      agent_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, agent_info, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.agent_info_ = agent_info;
  // @@protoc_insertion_point(field_set_allocated:communicator_objects.AgentInfoActionPairProto.agent_info)
}

// .communicator_objects.AgentActionProto action_info = 2;
inline bool AgentInfoActionPairProto::has_action_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.action_info_ != nullptr);
  return value;
}
inline const ::communicator_objects::AgentActionProto& AgentInfoActionPairProto::_internal_action_info() const {
  const ::communicator_objects::AgentActionProto* p = _impl_.action_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::communicator_objects::AgentActionProto&>(
      ::communicator_objects::_AgentActionProto_default_instance_);
}
inline const ::communicator_objects::AgentActionProto& AgentInfoActionPairProto::action_info() const {
  // @@protoc_insertion_point(field_get:communicator_objects.AgentInfoActionPairProto.action_info)
  return _internal_action_info();
}
inline void AgentInfoActionPairProto::unsafe_arena_set_allocated_action_info(
    ::communicator_objects::AgentActionProto* action_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.action_info_);
  }
  _impl_.action_info_ = action_info;
  if (action_info) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:communicator_objects.AgentInfoActionPairProto.action_info)
}
inline ::communicator_objects::AgentActionProto* AgentInfoActionPairProto::release_action_info() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::communicator_objects::AgentActionProto* temp = _impl_.action_info_;
  _impl_.action_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::communicator_objects::AgentActionProto* AgentInfoActionPairProto::unsafe_arena_release_action_info() {
  // @@protoc_insertion_point(field_release:communicator_objects.AgentInfoActionPairProto.action_info)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::communicator_objects::AgentActionProto* temp = _impl_.action_info_;
  _impl_.action_info_ = nullptr;
  return temp;
}
inline ::communicator_objects::AgentActionProto* AgentInfoActionPairProto::_internal_mutable_action_info() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.action_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::communicator_objects::AgentActionProto>(GetArenaForAllocation());
    _impl_.action_info_ = p;
  }
  return _impl_.action_info_;
}
inline ::communicator_objects::AgentActionProto* AgentInfoActionPairProto::mutable_action_info() {
  ::communicator_objects::AgentActionProto* _msg = _internal_mutable_action_info();
  // @@protoc_insertion_point(field_mutable:communicator_objects.AgentInfoActionPairProto.action_info)
  return _msg;
}
inline void AgentInfoActionPairProto::set_allocated_action_info(::communicator_objects::AgentActionProto* action_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.action_info_);
  }
  if (action_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(action_info));
    if (message_arena != submessage_arena) {
      action_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, action_info, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.action_info_ = action_info;
  // @@protoc_insertion_point(field_set_allocated:communicator_objects.AgentInfoActionPairProto.action_info)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace communicator_objects


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ueagents_5fenvs_2fcommunicator_5fobjects_2fagent_5finfo_5faction_5fpair_2eproto_2epb_2eh
