// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ueagents_envs/communicator_objects/unreal_rl_initialization_input.proto

#include "ueagents_envs/communicator_objects/unreal_rl_initialization_input.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace communicator_objects {
template <typename>
PROTOBUF_CONSTEXPR UnrealRLInitializationInputProto::UnrealRLInitializationInputProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.communication_version_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.package_version_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.seed_)*/ 0

  , /*decltype(_impl_.num_areas_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnrealRLInitializationInputProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnrealRLInitializationInputProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnrealRLInitializationInputProtoDefaultTypeInternal() {}
  union {
    UnrealRLInitializationInputProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnrealRLInitializationInputProtoDefaultTypeInternal _UnrealRLInitializationInputProto_default_instance_;
}  // namespace communicator_objects
static ::_pb::Metadata file_level_metadata_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto = nullptr;
const ::uint32_t TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::communicator_objects::UnrealRLInitializationInputProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::communicator_objects::UnrealRLInitializationInputProto, _impl_.seed_),
    PROTOBUF_FIELD_OFFSET(::communicator_objects::UnrealRLInitializationInputProto, _impl_.communication_version_),
    PROTOBUF_FIELD_OFFSET(::communicator_objects::UnrealRLInitializationInputProto, _impl_.package_version_),
    PROTOBUF_FIELD_OFFSET(::communicator_objects::UnrealRLInitializationInputProto, _impl_.num_areas_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::communicator_objects::UnrealRLInitializationInputProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::communicator_objects::_UnrealRLInitializationInputProto_default_instance_._instance,
};
const char descriptor_table_protodef_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\nGueagents_envs/communicator_objects/unr"
    "eal_rl_initialization_input.proto\022\024commu"
    "nicator_objects\"{\n UnrealRLInitializatio"
    "nInputProto\022\014\n\004seed\030\001 \001(\005\022\035\n\025communicati"
    "on_version\030\002 \001(\t\022\027\n\017package_version\030\003 \001("
    "\t\022\021\n\tnum_areas\030\004 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto = {
    false,
    false,
    228,
    descriptor_table_protodef_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto,
    "ueagents_envs/communicator_objects/unreal_rl_initialization_input.proto",
    &descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto::offsets,
    file_level_metadata_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto,
    file_level_enum_descriptors_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto,
    file_level_service_descriptors_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto_getter() {
  return &descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto(&descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto);
namespace communicator_objects {
// ===================================================================

class UnrealRLInitializationInputProto::_Internal {
 public:
};

UnrealRLInitializationInputProto::UnrealRLInitializationInputProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:communicator_objects.UnrealRLInitializationInputProto)
}
UnrealRLInitializationInputProto::UnrealRLInitializationInputProto(const UnrealRLInitializationInputProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnrealRLInitializationInputProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.communication_version_) {}

    , decltype(_impl_.package_version_) {}

    , decltype(_impl_.seed_) {}

    , decltype(_impl_.num_areas_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.communication_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.communication_version_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_communication_version().empty()) {
    _this->_impl_.communication_version_.Set(from._internal_communication_version(), _this->GetArenaForAllocation());
  }
  _impl_.package_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.package_version_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_package_version().empty()) {
    _this->_impl_.package_version_.Set(from._internal_package_version(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.seed_, &from._impl_.seed_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.num_areas_) -
    reinterpret_cast<char*>(&_impl_.seed_)) + sizeof(_impl_.num_areas_));
  // @@protoc_insertion_point(copy_constructor:communicator_objects.UnrealRLInitializationInputProto)
}

inline void UnrealRLInitializationInputProto::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.communication_version_) {}

    , decltype(_impl_.package_version_) {}

    , decltype(_impl_.seed_) { 0 }

    , decltype(_impl_.num_areas_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.communication_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.communication_version_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.package_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.package_version_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

UnrealRLInitializationInputProto::~UnrealRLInitializationInputProto() {
  // @@protoc_insertion_point(destructor:communicator_objects.UnrealRLInitializationInputProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnrealRLInitializationInputProto::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.communication_version_.Destroy();
  _impl_.package_version_.Destroy();
}

void UnrealRLInitializationInputProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnrealRLInitializationInputProto::Clear() {
// @@protoc_insertion_point(message_clear_start:communicator_objects.UnrealRLInitializationInputProto)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.communication_version_.ClearToEmpty();
  _impl_.package_version_.ClearToEmpty();
  ::memset(&_impl_.seed_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.num_areas_) -
      reinterpret_cast<char*>(&_impl_.seed_)) + sizeof(_impl_.num_areas_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnrealRLInitializationInputProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 seed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _impl_.seed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // string communication_version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_communication_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "communicator_objects.UnrealRLInitializationInputProto.communication_version"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string package_version = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_package_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "communicator_objects.UnrealRLInitializationInputProto.package_version"));
        } else {
          goto handle_unusual;
        }
        continue;
      // int32 num_areas = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _impl_.num_areas_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* UnrealRLInitializationInputProto::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:communicator_objects.UnrealRLInitializationInputProto)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 seed = 1;
  if (this->_internal_seed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        1, this->_internal_seed(), target);
  }

  // string communication_version = 2;
  if (!this->_internal_communication_version().empty()) {
    const std::string& _s = this->_internal_communication_version();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "communicator_objects.UnrealRLInitializationInputProto.communication_version");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string package_version = 3;
  if (!this->_internal_package_version().empty()) {
    const std::string& _s = this->_internal_package_version();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "communicator_objects.UnrealRLInitializationInputProto.package_version");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 num_areas = 4;
  if (this->_internal_num_areas() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        4, this->_internal_num_areas(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:communicator_objects.UnrealRLInitializationInputProto)
  return target;
}

::size_t UnrealRLInitializationInputProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:communicator_objects.UnrealRLInitializationInputProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string communication_version = 2;
  if (!this->_internal_communication_version().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_communication_version());
  }

  // string package_version = 3;
  if (!this->_internal_package_version().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_package_version());
  }

  // int32 seed = 1;
  if (this->_internal_seed() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_seed());
  }

  // int32 num_areas = 4;
  if (this->_internal_num_areas() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_num_areas());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnrealRLInitializationInputProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnrealRLInitializationInputProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnrealRLInitializationInputProto::GetClassData() const { return &_class_data_; }


void UnrealRLInitializationInputProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnrealRLInitializationInputProto*>(&to_msg);
  auto& from = static_cast<const UnrealRLInitializationInputProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:communicator_objects.UnrealRLInitializationInputProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_communication_version().empty()) {
    _this->_internal_set_communication_version(from._internal_communication_version());
  }
  if (!from._internal_package_version().empty()) {
    _this->_internal_set_package_version(from._internal_package_version());
  }
  if (from._internal_seed() != 0) {
    _this->_internal_set_seed(from._internal_seed());
  }
  if (from._internal_num_areas() != 0) {
    _this->_internal_set_num_areas(from._internal_num_areas());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnrealRLInitializationInputProto::CopyFrom(const UnrealRLInitializationInputProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:communicator_objects.UnrealRLInitializationInputProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnrealRLInitializationInputProto::IsInitialized() const {
  return true;
}

void UnrealRLInitializationInputProto::InternalSwap(UnrealRLInitializationInputProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.communication_version_, lhs_arena,
                                       &other->_impl_.communication_version_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.package_version_, lhs_arena,
                                       &other->_impl_.package_version_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UnrealRLInitializationInputProto, _impl_.num_areas_)
      + sizeof(UnrealRLInitializationInputProto::_impl_.num_areas_)
      - PROTOBUF_FIELD_OFFSET(UnrealRLInitializationInputProto, _impl_.seed_)>(
          reinterpret_cast<char*>(&_impl_.seed_),
          reinterpret_cast<char*>(&other->_impl_.seed_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UnrealRLInitializationInputProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto_getter, &descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto_once,
      file_level_metadata_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finitialization_5finput_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace communicator_objects
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::communicator_objects::UnrealRLInitializationInputProto*
Arena::CreateMaybeMessage< ::communicator_objects::UnrealRLInitializationInputProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::communicator_objects::UnrealRLInitializationInputProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
