// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mlagents_envs/communicator_objects/unreal_output.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5foutput_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5foutput_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "mlagents_envs/communicator_objects/unreal_rl_output.pb.h"
#include "mlagents_envs/communicator_objects/unreal_rl_initialization_output.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5foutput_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5foutput_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5foutput_2eproto;
namespace communicator_objects {
class UnrealOutputProto;
struct UnrealOutputProtoDefaultTypeInternal;
extern UnrealOutputProtoDefaultTypeInternal _UnrealOutputProto_default_instance_;
}  // namespace communicator_objects
PROTOBUF_NAMESPACE_OPEN
template <>
::communicator_objects::UnrealOutputProto* Arena::CreateMaybeMessage<::communicator_objects::UnrealOutputProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace communicator_objects {

// ===================================================================


// -------------------------------------------------------------------

class UnrealOutputProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:communicator_objects.UnrealOutputProto) */ {
 public:
  inline UnrealOutputProto() : UnrealOutputProto(nullptr) {}
  ~UnrealOutputProto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UnrealOutputProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnrealOutputProto(const UnrealOutputProto& from);
  UnrealOutputProto(UnrealOutputProto&& from) noexcept
    : UnrealOutputProto() {
    *this = ::std::move(from);
  }

  inline UnrealOutputProto& operator=(const UnrealOutputProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnrealOutputProto& operator=(UnrealOutputProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnrealOutputProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnrealOutputProto* internal_default_instance() {
    return reinterpret_cast<const UnrealOutputProto*>(
               &_UnrealOutputProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UnrealOutputProto& a, UnrealOutputProto& b) {
    a.Swap(&b);
  }
  inline void Swap(UnrealOutputProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnrealOutputProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnrealOutputProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnrealOutputProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnrealOutputProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnrealOutputProto& from) {
    UnrealOutputProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnrealOutputProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "communicator_objects.UnrealOutputProto";
  }
  protected:
  explicit UnrealOutputProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRlOutputFieldNumber = 1,
    kRlInitializationOutputFieldNumber = 2,
  };
  // .communicator_objects.UnrealRLOutputProto rl_output = 1;
  bool has_rl_output() const;
  void clear_rl_output() ;
  const ::communicator_objects::UnrealRLOutputProto& rl_output() const;
  PROTOBUF_NODISCARD ::communicator_objects::UnrealRLOutputProto* release_rl_output();
  ::communicator_objects::UnrealRLOutputProto* mutable_rl_output();
  void set_allocated_rl_output(::communicator_objects::UnrealRLOutputProto* rl_output);
  private:
  const ::communicator_objects::UnrealRLOutputProto& _internal_rl_output() const;
  ::communicator_objects::UnrealRLOutputProto* _internal_mutable_rl_output();
  public:
  void unsafe_arena_set_allocated_rl_output(
      ::communicator_objects::UnrealRLOutputProto* rl_output);
  ::communicator_objects::UnrealRLOutputProto* unsafe_arena_release_rl_output();
  // .communicator_objects.UnrealRLInitializationOutputProto rl_initialization_output = 2;
  bool has_rl_initialization_output() const;
  void clear_rl_initialization_output() ;
  const ::communicator_objects::UnrealRLInitializationOutputProto& rl_initialization_output() const;
  PROTOBUF_NODISCARD ::communicator_objects::UnrealRLInitializationOutputProto* release_rl_initialization_output();
  ::communicator_objects::UnrealRLInitializationOutputProto* mutable_rl_initialization_output();
  void set_allocated_rl_initialization_output(::communicator_objects::UnrealRLInitializationOutputProto* rl_initialization_output);
  private:
  const ::communicator_objects::UnrealRLInitializationOutputProto& _internal_rl_initialization_output() const;
  ::communicator_objects::UnrealRLInitializationOutputProto* _internal_mutable_rl_initialization_output();
  public:
  void unsafe_arena_set_allocated_rl_initialization_output(
      ::communicator_objects::UnrealRLInitializationOutputProto* rl_initialization_output);
  ::communicator_objects::UnrealRLInitializationOutputProto* unsafe_arena_release_rl_initialization_output();
  // @@protoc_insertion_point(class_scope:communicator_objects.UnrealOutputProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::communicator_objects::UnrealRLOutputProto* rl_output_;
    ::communicator_objects::UnrealRLInitializationOutputProto* rl_initialization_output_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5foutput_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UnrealOutputProto

// .communicator_objects.UnrealRLOutputProto rl_output = 1;
inline bool UnrealOutputProto::has_rl_output() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rl_output_ != nullptr);
  return value;
}
inline const ::communicator_objects::UnrealRLOutputProto& UnrealOutputProto::_internal_rl_output() const {
  const ::communicator_objects::UnrealRLOutputProto* p = _impl_.rl_output_;
  return p != nullptr ? *p : reinterpret_cast<const ::communicator_objects::UnrealRLOutputProto&>(
      ::communicator_objects::_UnrealRLOutputProto_default_instance_);
}
inline const ::communicator_objects::UnrealRLOutputProto& UnrealOutputProto::rl_output() const {
  // @@protoc_insertion_point(field_get:communicator_objects.UnrealOutputProto.rl_output)
  return _internal_rl_output();
}
inline void UnrealOutputProto::unsafe_arena_set_allocated_rl_output(
    ::communicator_objects::UnrealRLOutputProto* rl_output) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_output_);
  }
  _impl_.rl_output_ = rl_output;
  if (rl_output) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:communicator_objects.UnrealOutputProto.rl_output)
}
inline ::communicator_objects::UnrealRLOutputProto* UnrealOutputProto::release_rl_output() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::communicator_objects::UnrealRLOutputProto* temp = _impl_.rl_output_;
  _impl_.rl_output_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::communicator_objects::UnrealRLOutputProto* UnrealOutputProto::unsafe_arena_release_rl_output() {
  // @@protoc_insertion_point(field_release:communicator_objects.UnrealOutputProto.rl_output)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::communicator_objects::UnrealRLOutputProto* temp = _impl_.rl_output_;
  _impl_.rl_output_ = nullptr;
  return temp;
}
inline ::communicator_objects::UnrealRLOutputProto* UnrealOutputProto::_internal_mutable_rl_output() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.rl_output_ == nullptr) {
    auto* p = CreateMaybeMessage<::communicator_objects::UnrealRLOutputProto>(GetArenaForAllocation());
    _impl_.rl_output_ = p;
  }
  return _impl_.rl_output_;
}
inline ::communicator_objects::UnrealRLOutputProto* UnrealOutputProto::mutable_rl_output() {
  ::communicator_objects::UnrealRLOutputProto* _msg = _internal_mutable_rl_output();
  // @@protoc_insertion_point(field_mutable:communicator_objects.UnrealOutputProto.rl_output)
  return _msg;
}
inline void UnrealOutputProto::set_allocated_rl_output(::communicator_objects::UnrealRLOutputProto* rl_output) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_output_);
  }
  if (rl_output) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rl_output));
    if (message_arena != submessage_arena) {
      rl_output = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rl_output, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.rl_output_ = rl_output;
  // @@protoc_insertion_point(field_set_allocated:communicator_objects.UnrealOutputProto.rl_output)
}

// .communicator_objects.UnrealRLInitializationOutputProto rl_initialization_output = 2;
inline bool UnrealOutputProto::has_rl_initialization_output() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rl_initialization_output_ != nullptr);
  return value;
}
inline const ::communicator_objects::UnrealRLInitializationOutputProto& UnrealOutputProto::_internal_rl_initialization_output() const {
  const ::communicator_objects::UnrealRLInitializationOutputProto* p = _impl_.rl_initialization_output_;
  return p != nullptr ? *p : reinterpret_cast<const ::communicator_objects::UnrealRLInitializationOutputProto&>(
      ::communicator_objects::_UnrealRLInitializationOutputProto_default_instance_);
}
inline const ::communicator_objects::UnrealRLInitializationOutputProto& UnrealOutputProto::rl_initialization_output() const {
  // @@protoc_insertion_point(field_get:communicator_objects.UnrealOutputProto.rl_initialization_output)
  return _internal_rl_initialization_output();
}
inline void UnrealOutputProto::unsafe_arena_set_allocated_rl_initialization_output(
    ::communicator_objects::UnrealRLInitializationOutputProto* rl_initialization_output) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_initialization_output_);
  }
  _impl_.rl_initialization_output_ = rl_initialization_output;
  if (rl_initialization_output) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:communicator_objects.UnrealOutputProto.rl_initialization_output)
}
inline ::communicator_objects::UnrealRLInitializationOutputProto* UnrealOutputProto::release_rl_initialization_output() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::communicator_objects::UnrealRLInitializationOutputProto* temp = _impl_.rl_initialization_output_;
  _impl_.rl_initialization_output_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::communicator_objects::UnrealRLInitializationOutputProto* UnrealOutputProto::unsafe_arena_release_rl_initialization_output() {
  // @@protoc_insertion_point(field_release:communicator_objects.UnrealOutputProto.rl_initialization_output)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::communicator_objects::UnrealRLInitializationOutputProto* temp = _impl_.rl_initialization_output_;
  _impl_.rl_initialization_output_ = nullptr;
  return temp;
}
inline ::communicator_objects::UnrealRLInitializationOutputProto* UnrealOutputProto::_internal_mutable_rl_initialization_output() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.rl_initialization_output_ == nullptr) {
    auto* p = CreateMaybeMessage<::communicator_objects::UnrealRLInitializationOutputProto>(GetArenaForAllocation());
    _impl_.rl_initialization_output_ = p;
  }
  return _impl_.rl_initialization_output_;
}
inline ::communicator_objects::UnrealRLInitializationOutputProto* UnrealOutputProto::mutable_rl_initialization_output() {
  ::communicator_objects::UnrealRLInitializationOutputProto* _msg = _internal_mutable_rl_initialization_output();
  // @@protoc_insertion_point(field_mutable:communicator_objects.UnrealOutputProto.rl_initialization_output)
  return _msg;
}
inline void UnrealOutputProto::set_allocated_rl_initialization_output(::communicator_objects::UnrealRLInitializationOutputProto* rl_initialization_output) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_initialization_output_);
  }
  if (rl_initialization_output) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rl_initialization_output));
    if (message_arena != submessage_arena) {
      rl_initialization_output = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rl_initialization_output, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.rl_initialization_output_ = rl_initialization_output;
  // @@protoc_insertion_point(field_set_allocated:communicator_objects.UnrealOutputProto.rl_initialization_output)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace communicator_objects


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5foutput_2eproto_2epb_2eh
