// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mlagents_envs/communicator_objects/unreal_input.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5finput_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5finput_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "mlagents_envs/communicator_objects/unreal_rl_input.pb.h"
#include "mlagents_envs/communicator_objects/unreal_rl_initialization_input.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5finput_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5finput_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5finput_2eproto;
namespace communicator_objects {
class UnrealInputProto;
struct UnrealInputProtoDefaultTypeInternal;
extern UnrealInputProtoDefaultTypeInternal _UnrealInputProto_default_instance_;
}  // namespace communicator_objects
PROTOBUF_NAMESPACE_OPEN
template <>
::communicator_objects::UnrealInputProto* Arena::CreateMaybeMessage<::communicator_objects::UnrealInputProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace communicator_objects {

// ===================================================================


// -------------------------------------------------------------------

class UnrealInputProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:communicator_objects.UnrealInputProto) */ {
 public:
  inline UnrealInputProto() : UnrealInputProto(nullptr) {}
  ~UnrealInputProto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UnrealInputProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnrealInputProto(const UnrealInputProto& from);
  UnrealInputProto(UnrealInputProto&& from) noexcept
    : UnrealInputProto() {
    *this = ::std::move(from);
  }

  inline UnrealInputProto& operator=(const UnrealInputProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnrealInputProto& operator=(UnrealInputProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnrealInputProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnrealInputProto* internal_default_instance() {
    return reinterpret_cast<const UnrealInputProto*>(
               &_UnrealInputProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UnrealInputProto& a, UnrealInputProto& b) {
    a.Swap(&b);
  }
  inline void Swap(UnrealInputProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnrealInputProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnrealInputProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnrealInputProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnrealInputProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnrealInputProto& from) {
    UnrealInputProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnrealInputProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "communicator_objects.UnrealInputProto";
  }
  protected:
  explicit UnrealInputProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRlInputFieldNumber = 1,
    kRlInitializationInputFieldNumber = 2,
  };
  // .communicator_objects.UnrealRLInputProto rl_input = 1;
  bool has_rl_input() const;
  void clear_rl_input() ;
  const ::communicator_objects::UnrealRLInputProto& rl_input() const;
  PROTOBUF_NODISCARD ::communicator_objects::UnrealRLInputProto* release_rl_input();
  ::communicator_objects::UnrealRLInputProto* mutable_rl_input();
  void set_allocated_rl_input(::communicator_objects::UnrealRLInputProto* rl_input);
  private:
  const ::communicator_objects::UnrealRLInputProto& _internal_rl_input() const;
  ::communicator_objects::UnrealRLInputProto* _internal_mutable_rl_input();
  public:
  void unsafe_arena_set_allocated_rl_input(
      ::communicator_objects::UnrealRLInputProto* rl_input);
  ::communicator_objects::UnrealRLInputProto* unsafe_arena_release_rl_input();
  // .communicator_objects.UnrealRLInitializationInputProto rl_initialization_input = 2;
  bool has_rl_initialization_input() const;
  void clear_rl_initialization_input() ;
  const ::communicator_objects::UnrealRLInitializationInputProto& rl_initialization_input() const;
  PROTOBUF_NODISCARD ::communicator_objects::UnrealRLInitializationInputProto* release_rl_initialization_input();
  ::communicator_objects::UnrealRLInitializationInputProto* mutable_rl_initialization_input();
  void set_allocated_rl_initialization_input(::communicator_objects::UnrealRLInitializationInputProto* rl_initialization_input);
  private:
  const ::communicator_objects::UnrealRLInitializationInputProto& _internal_rl_initialization_input() const;
  ::communicator_objects::UnrealRLInitializationInputProto* _internal_mutable_rl_initialization_input();
  public:
  void unsafe_arena_set_allocated_rl_initialization_input(
      ::communicator_objects::UnrealRLInitializationInputProto* rl_initialization_input);
  ::communicator_objects::UnrealRLInitializationInputProto* unsafe_arena_release_rl_initialization_input();
  // @@protoc_insertion_point(class_scope:communicator_objects.UnrealInputProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::communicator_objects::UnrealRLInputProto* rl_input_;
    ::communicator_objects::UnrealRLInitializationInputProto* rl_initialization_input_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5finput_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UnrealInputProto

// .communicator_objects.UnrealRLInputProto rl_input = 1;
inline bool UnrealInputProto::has_rl_input() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rl_input_ != nullptr);
  return value;
}
inline const ::communicator_objects::UnrealRLInputProto& UnrealInputProto::_internal_rl_input() const {
  const ::communicator_objects::UnrealRLInputProto* p = _impl_.rl_input_;
  return p != nullptr ? *p : reinterpret_cast<const ::communicator_objects::UnrealRLInputProto&>(
      ::communicator_objects::_UnrealRLInputProto_default_instance_);
}
inline const ::communicator_objects::UnrealRLInputProto& UnrealInputProto::rl_input() const {
  // @@protoc_insertion_point(field_get:communicator_objects.UnrealInputProto.rl_input)
  return _internal_rl_input();
}
inline void UnrealInputProto::unsafe_arena_set_allocated_rl_input(
    ::communicator_objects::UnrealRLInputProto* rl_input) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_input_);
  }
  _impl_.rl_input_ = rl_input;
  if (rl_input) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:communicator_objects.UnrealInputProto.rl_input)
}
inline ::communicator_objects::UnrealRLInputProto* UnrealInputProto::release_rl_input() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::communicator_objects::UnrealRLInputProto* temp = _impl_.rl_input_;
  _impl_.rl_input_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::communicator_objects::UnrealRLInputProto* UnrealInputProto::unsafe_arena_release_rl_input() {
  // @@protoc_insertion_point(field_release:communicator_objects.UnrealInputProto.rl_input)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::communicator_objects::UnrealRLInputProto* temp = _impl_.rl_input_;
  _impl_.rl_input_ = nullptr;
  return temp;
}
inline ::communicator_objects::UnrealRLInputProto* UnrealInputProto::_internal_mutable_rl_input() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.rl_input_ == nullptr) {
    auto* p = CreateMaybeMessage<::communicator_objects::UnrealRLInputProto>(GetArenaForAllocation());
    _impl_.rl_input_ = p;
  }
  return _impl_.rl_input_;
}
inline ::communicator_objects::UnrealRLInputProto* UnrealInputProto::mutable_rl_input() {
  ::communicator_objects::UnrealRLInputProto* _msg = _internal_mutable_rl_input();
  // @@protoc_insertion_point(field_mutable:communicator_objects.UnrealInputProto.rl_input)
  return _msg;
}
inline void UnrealInputProto::set_allocated_rl_input(::communicator_objects::UnrealRLInputProto* rl_input) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_input_);
  }
  if (rl_input) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rl_input));
    if (message_arena != submessage_arena) {
      rl_input = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rl_input, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.rl_input_ = rl_input;
  // @@protoc_insertion_point(field_set_allocated:communicator_objects.UnrealInputProto.rl_input)
}

// .communicator_objects.UnrealRLInitializationInputProto rl_initialization_input = 2;
inline bool UnrealInputProto::has_rl_initialization_input() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.rl_initialization_input_ != nullptr);
  return value;
}
inline const ::communicator_objects::UnrealRLInitializationInputProto& UnrealInputProto::_internal_rl_initialization_input() const {
  const ::communicator_objects::UnrealRLInitializationInputProto* p = _impl_.rl_initialization_input_;
  return p != nullptr ? *p : reinterpret_cast<const ::communicator_objects::UnrealRLInitializationInputProto&>(
      ::communicator_objects::_UnrealRLInitializationInputProto_default_instance_);
}
inline const ::communicator_objects::UnrealRLInitializationInputProto& UnrealInputProto::rl_initialization_input() const {
  // @@protoc_insertion_point(field_get:communicator_objects.UnrealInputProto.rl_initialization_input)
  return _internal_rl_initialization_input();
}
inline void UnrealInputProto::unsafe_arena_set_allocated_rl_initialization_input(
    ::communicator_objects::UnrealRLInitializationInputProto* rl_initialization_input) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_initialization_input_);
  }
  _impl_.rl_initialization_input_ = rl_initialization_input;
  if (rl_initialization_input) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:communicator_objects.UnrealInputProto.rl_initialization_input)
}
inline ::communicator_objects::UnrealRLInitializationInputProto* UnrealInputProto::release_rl_initialization_input() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::communicator_objects::UnrealRLInitializationInputProto* temp = _impl_.rl_initialization_input_;
  _impl_.rl_initialization_input_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::communicator_objects::UnrealRLInitializationInputProto* UnrealInputProto::unsafe_arena_release_rl_initialization_input() {
  // @@protoc_insertion_point(field_release:communicator_objects.UnrealInputProto.rl_initialization_input)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::communicator_objects::UnrealRLInitializationInputProto* temp = _impl_.rl_initialization_input_;
  _impl_.rl_initialization_input_ = nullptr;
  return temp;
}
inline ::communicator_objects::UnrealRLInitializationInputProto* UnrealInputProto::_internal_mutable_rl_initialization_input() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.rl_initialization_input_ == nullptr) {
    auto* p = CreateMaybeMessage<::communicator_objects::UnrealRLInitializationInputProto>(GetArenaForAllocation());
    _impl_.rl_initialization_input_ = p;
  }
  return _impl_.rl_initialization_input_;
}
inline ::communicator_objects::UnrealRLInitializationInputProto* UnrealInputProto::mutable_rl_initialization_input() {
  ::communicator_objects::UnrealRLInitializationInputProto* _msg = _internal_mutable_rl_initialization_input();
  // @@protoc_insertion_point(field_mutable:communicator_objects.UnrealInputProto.rl_initialization_input)
  return _msg;
}
inline void UnrealInputProto::set_allocated_rl_initialization_input(::communicator_objects::UnrealRLInitializationInputProto* rl_initialization_input) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.rl_initialization_input_);
  }
  if (rl_initialization_input) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rl_initialization_input));
    if (message_arena != submessage_arena) {
      rl_initialization_input = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rl_initialization_input, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.rl_initialization_input_ = rl_initialization_input;
  // @@protoc_insertion_point(field_set_allocated:communicator_objects.UnrealInputProto.rl_initialization_input)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace communicator_objects


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_mlagents_5fenvs_2fcommunicator_5fobjects_2funreal_5finput_2eproto_2epb_2eh
