// Copyright © 2025 Stephane Capponi and individual contributors. All Rights Reserved.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ueagents_envs/communicator_objects/unreal_rl_input.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
#include "ueagents_envs/communicator_objects/agent_action.pb.h"
#include "ueagents_envs/communicator_objects/command.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto;
namespace communicator_objects {
class UnrealRLInputProto;
struct UnrealRLInputProtoDefaultTypeInternal;
extern UnrealRLInputProtoDefaultTypeInternal _UnrealRLInputProto_default_instance_;
class UnrealRLInputProto_AgentActionsEntry_DoNotUse;
struct UnrealRLInputProto_AgentActionsEntry_DoNotUseDefaultTypeInternal;
extern UnrealRLInputProto_AgentActionsEntry_DoNotUseDefaultTypeInternal _UnrealRLInputProto_AgentActionsEntry_DoNotUse_default_instance_;
class UnrealRLInputProto_ListAgentActionProto;
struct UnrealRLInputProto_ListAgentActionProtoDefaultTypeInternal;
extern UnrealRLInputProto_ListAgentActionProtoDefaultTypeInternal _UnrealRLInputProto_ListAgentActionProto_default_instance_;
}  // namespace communicator_objects
PROTOBUF_NAMESPACE_OPEN
template <>
::communicator_objects::UnrealRLInputProto* Arena::CreateMaybeMessage<::communicator_objects::UnrealRLInputProto>(Arena*);
template <>
::communicator_objects::UnrealRLInputProto_AgentActionsEntry_DoNotUse* Arena::CreateMaybeMessage<::communicator_objects::UnrealRLInputProto_AgentActionsEntry_DoNotUse>(Arena*);
template <>
::communicator_objects::UnrealRLInputProto_ListAgentActionProto* Arena::CreateMaybeMessage<::communicator_objects::UnrealRLInputProto_ListAgentActionProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace communicator_objects {

// ===================================================================


// -------------------------------------------------------------------

class UnrealRLInputProto_ListAgentActionProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:communicator_objects.UnrealRLInputProto.ListAgentActionProto) */ {
 public:
  inline UnrealRLInputProto_ListAgentActionProto() : UnrealRLInputProto_ListAgentActionProto(nullptr) {}
  ~UnrealRLInputProto_ListAgentActionProto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UnrealRLInputProto_ListAgentActionProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnrealRLInputProto_ListAgentActionProto(const UnrealRLInputProto_ListAgentActionProto& from);
  UnrealRLInputProto_ListAgentActionProto(UnrealRLInputProto_ListAgentActionProto&& from) noexcept
    : UnrealRLInputProto_ListAgentActionProto() {
    *this = ::std::move(from);
  }

  inline UnrealRLInputProto_ListAgentActionProto& operator=(const UnrealRLInputProto_ListAgentActionProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnrealRLInputProto_ListAgentActionProto& operator=(UnrealRLInputProto_ListAgentActionProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnrealRLInputProto_ListAgentActionProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnrealRLInputProto_ListAgentActionProto* internal_default_instance() {
    return reinterpret_cast<const UnrealRLInputProto_ListAgentActionProto*>(
               &_UnrealRLInputProto_ListAgentActionProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UnrealRLInputProto_ListAgentActionProto& a, UnrealRLInputProto_ListAgentActionProto& b) {
    a.Swap(&b);
  }
  inline void Swap(UnrealRLInputProto_ListAgentActionProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnrealRLInputProto_ListAgentActionProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnrealRLInputProto_ListAgentActionProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnrealRLInputProto_ListAgentActionProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnrealRLInputProto_ListAgentActionProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnrealRLInputProto_ListAgentActionProto& from) {
    UnrealRLInputProto_ListAgentActionProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnrealRLInputProto_ListAgentActionProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "communicator_objects.UnrealRLInputProto.ListAgentActionProto";
  }
  protected:
  explicit UnrealRLInputProto_ListAgentActionProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // repeated .communicator_objects.AgentActionProto value = 1;
  int value_size() const;
  private:
  int _internal_value_size() const;

  public:
  void clear_value() ;
  ::communicator_objects::AgentActionProto* mutable_value(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::communicator_objects::AgentActionProto >*
      mutable_value();
  private:
  const ::communicator_objects::AgentActionProto& _internal_value(int index) const;
  ::communicator_objects::AgentActionProto* _internal_add_value();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::communicator_objects::AgentActionProto>& _internal_value() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::communicator_objects::AgentActionProto>* _internal_mutable_value();
  public:
  const ::communicator_objects::AgentActionProto& value(int index) const;
  ::communicator_objects::AgentActionProto* add_value();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::communicator_objects::AgentActionProto >&
      value() const;
  // @@protoc_insertion_point(class_scope:communicator_objects.UnrealRLInputProto.ListAgentActionProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::communicator_objects::AgentActionProto > value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto;
};// -------------------------------------------------------------------

class UnrealRLInputProto_AgentActionsEntry_DoNotUse final : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<UnrealRLInputProto_AgentActionsEntry_DoNotUse,
    std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<UnrealRLInputProto_AgentActionsEntry_DoNotUse,
    std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  UnrealRLInputProto_AgentActionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UnrealRLInputProto_AgentActionsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit UnrealRLInputProto_AgentActionsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const UnrealRLInputProto_AgentActionsEntry_DoNotUse& other);
  static const UnrealRLInputProto_AgentActionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const UnrealRLInputProto_AgentActionsEntry_DoNotUse*>(&_UnrealRLInputProto_AgentActionsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "communicator_objects.UnrealRLInputProto.AgentActionsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto;
};
// -------------------------------------------------------------------

class UnrealRLInputProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:communicator_objects.UnrealRLInputProto) */ {
 public:
  inline UnrealRLInputProto() : UnrealRLInputProto(nullptr) {}
  ~UnrealRLInputProto() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UnrealRLInputProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnrealRLInputProto(const UnrealRLInputProto& from);
  UnrealRLInputProto(UnrealRLInputProto&& from) noexcept
    : UnrealRLInputProto() {
    *this = ::std::move(from);
  }

  inline UnrealRLInputProto& operator=(const UnrealRLInputProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnrealRLInputProto& operator=(UnrealRLInputProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnrealRLInputProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnrealRLInputProto* internal_default_instance() {
    return reinterpret_cast<const UnrealRLInputProto*>(
               &_UnrealRLInputProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(UnrealRLInputProto& a, UnrealRLInputProto& b) {
    a.Swap(&b);
  }
  inline void Swap(UnrealRLInputProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnrealRLInputProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnrealRLInputProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnrealRLInputProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnrealRLInputProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnrealRLInputProto& from) {
    UnrealRLInputProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnrealRLInputProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "communicator_objects.UnrealRLInputProto";
  }
  protected:
  explicit UnrealRLInputProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UnrealRLInputProto_ListAgentActionProto ListAgentActionProto;

  // accessors -------------------------------------------------------

  enum : int {
    kAgentActionsFieldNumber = 1,
    kSideChannelFieldNumber = 3,
    kCommandFieldNumber = 2,
  };
  // map<string, .communicator_objects.UnrealRLInputProto.ListAgentActionProto> agent_actions = 1;
  int agent_actions_size() const;
  private:
  int _internal_agent_actions_size() const;

  public:
  void clear_agent_actions() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >&
      _internal_agent_actions() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >*
      _internal_mutable_agent_actions();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >&
      agent_actions() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >*
      mutable_agent_actions();
  // bytes side_channel = 3;
  void clear_side_channel() ;
  const std::string& side_channel() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_side_channel(Arg_&& arg, Args_... args);
  std::string* mutable_side_channel();
  PROTOBUF_NODISCARD std::string* release_side_channel();
  void set_allocated_side_channel(std::string* ptr);

  private:
  const std::string& _internal_side_channel() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_side_channel(
      const std::string& value);
  std::string* _internal_mutable_side_channel();

  public:
  // .communicator_objects.CommandProto command = 2;
  void clear_command() ;
  ::communicator_objects::CommandProto command() const;
  void set_command(::communicator_objects::CommandProto value);

  private:
  ::communicator_objects::CommandProto _internal_command() const;
  void _internal_set_command(::communicator_objects::CommandProto value);

  public:
  // @@protoc_insertion_point(class_scope:communicator_objects.UnrealRLInputProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        UnrealRLInputProto_AgentActionsEntry_DoNotUse,
        std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> agent_actions_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr side_channel_;
    int command_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UnrealRLInputProto_ListAgentActionProto

// repeated .communicator_objects.AgentActionProto value = 1;
inline int UnrealRLInputProto_ListAgentActionProto::_internal_value_size() const {
  return _impl_.value_.size();
}
inline int UnrealRLInputProto_ListAgentActionProto::value_size() const {
  return _internal_value_size();
}
inline ::communicator_objects::AgentActionProto* UnrealRLInputProto_ListAgentActionProto::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:communicator_objects.UnrealRLInputProto.ListAgentActionProto.value)
  return _internal_mutable_value()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::communicator_objects::AgentActionProto >*
UnrealRLInputProto_ListAgentActionProto::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:communicator_objects.UnrealRLInputProto.ListAgentActionProto.value)
  return _internal_mutable_value();
}
inline const ::communicator_objects::AgentActionProto& UnrealRLInputProto_ListAgentActionProto::_internal_value(int index) const {
  return _internal_value().Get(index);
}
inline const ::communicator_objects::AgentActionProto& UnrealRLInputProto_ListAgentActionProto::value(int index) const {
  // @@protoc_insertion_point(field_get:communicator_objects.UnrealRLInputProto.ListAgentActionProto.value)
  return _internal_value(index);
}
inline ::communicator_objects::AgentActionProto* UnrealRLInputProto_ListAgentActionProto::_internal_add_value() {
  return _internal_mutable_value()->Add();
}
inline ::communicator_objects::AgentActionProto* UnrealRLInputProto_ListAgentActionProto::add_value() {
  ::communicator_objects::AgentActionProto* _add = _internal_add_value();
  // @@protoc_insertion_point(field_add:communicator_objects.UnrealRLInputProto.ListAgentActionProto.value)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::communicator_objects::AgentActionProto >&
UnrealRLInputProto_ListAgentActionProto::value() const {
  // @@protoc_insertion_point(field_list:communicator_objects.UnrealRLInputProto.ListAgentActionProto.value)
  return _internal_value();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::communicator_objects::AgentActionProto>&
UnrealRLInputProto_ListAgentActionProto::_internal_value() const {
  return _impl_.value_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::communicator_objects::AgentActionProto>*
UnrealRLInputProto_ListAgentActionProto::_internal_mutable_value() {
  return &_impl_.value_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// UnrealRLInputProto

// map<string, .communicator_objects.UnrealRLInputProto.ListAgentActionProto> agent_actions = 1;
inline int UnrealRLInputProto::_internal_agent_actions_size() const {
  return _impl_.agent_actions_.size();
}
inline int UnrealRLInputProto::agent_actions_size() const {
  return _internal_agent_actions_size();
}
inline void UnrealRLInputProto::clear_agent_actions() {
  _impl_.agent_actions_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >&
UnrealRLInputProto::_internal_agent_actions() const {
  return _impl_.agent_actions_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >&
UnrealRLInputProto::agent_actions() const {
  // @@protoc_insertion_point(field_map:communicator_objects.UnrealRLInputProto.agent_actions)
  return _internal_agent_actions();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >*
UnrealRLInputProto::_internal_mutable_agent_actions() {
  return _impl_.agent_actions_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::communicator_objects::UnrealRLInputProto_ListAgentActionProto >*
UnrealRLInputProto::mutable_agent_actions() {
  // @@protoc_insertion_point(field_mutable_map:communicator_objects.UnrealRLInputProto.agent_actions)
  return _internal_mutable_agent_actions();
}

// .communicator_objects.CommandProto command = 2;
inline void UnrealRLInputProto::clear_command() {
  _impl_.command_ = 0;
}
inline ::communicator_objects::CommandProto UnrealRLInputProto::command() const {
  // @@protoc_insertion_point(field_get:communicator_objects.UnrealRLInputProto.command)
  return _internal_command();
}
inline void UnrealRLInputProto::set_command(::communicator_objects::CommandProto value) {
   _internal_set_command(value);
  // @@protoc_insertion_point(field_set:communicator_objects.UnrealRLInputProto.command)
}
inline ::communicator_objects::CommandProto UnrealRLInputProto::_internal_command() const {
  return static_cast<::communicator_objects::CommandProto>(_impl_.command_);
}
inline void UnrealRLInputProto::_internal_set_command(::communicator_objects::CommandProto value) {
  ;
  _impl_.command_ = value;
}

// bytes side_channel = 3;
inline void UnrealRLInputProto::clear_side_channel() {
  _impl_.side_channel_.ClearToEmpty();
}
inline const std::string& UnrealRLInputProto::side_channel() const {
  // @@protoc_insertion_point(field_get:communicator_objects.UnrealRLInputProto.side_channel)
  return _internal_side_channel();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UnrealRLInputProto::set_side_channel(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.side_channel_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:communicator_objects.UnrealRLInputProto.side_channel)
}
inline std::string* UnrealRLInputProto::mutable_side_channel() {
  std::string* _s = _internal_mutable_side_channel();
  // @@protoc_insertion_point(field_mutable:communicator_objects.UnrealRLInputProto.side_channel)
  return _s;
}
inline const std::string& UnrealRLInputProto::_internal_side_channel() const {
  return _impl_.side_channel_.Get();
}
inline void UnrealRLInputProto::_internal_set_side_channel(const std::string& value) {
  ;


  _impl_.side_channel_.Set(value, GetArenaForAllocation());
}
inline std::string* UnrealRLInputProto::_internal_mutable_side_channel() {
  ;
  return _impl_.side_channel_.Mutable( GetArenaForAllocation());
}
inline std::string* UnrealRLInputProto::release_side_channel() {
  // @@protoc_insertion_point(field_release:communicator_objects.UnrealRLInputProto.side_channel)
  return _impl_.side_channel_.Release();
}
inline void UnrealRLInputProto::set_allocated_side_channel(std::string* value) {
  _impl_.side_channel_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.side_channel_.IsDefault()) {
          _impl_.side_channel_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:communicator_objects.UnrealRLInputProto.side_channel)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace communicator_objects


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ueagents_5fenvs_2fcommunicator_5fobjects_2funreal_5frl_5finput_2eproto_2epb_2eh
