# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ueagents_envs/communicator_objects/observation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4ueagents_envs/communicator_objects/observation.proto\x12\x14\x63ommunicator_objects\"\xc4\x01\n\x10ObservationProto\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x46\n\nfloat_data\x18\x02 \x01(\x0b\x32\x30.communicator_objects.ObservationProto.FloatDataH\x00\x12\x1c\n\x14\x64imension_properties\x18\x03 \x03(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\x1a\x19\n\tFloatData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x42\x12\n\x10observation_data*4\n\x14ObservationTypeProto\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0f\n\x0bGOAL_SIGNAL\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ueagents_envs.communicator_objects.observation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_OBSERVATIONTYPEPROTO']._serialized_start=277
  _globals['_OBSERVATIONTYPEPROTO']._serialized_end=329
  _globals['_OBSERVATIONPROTO']._serialized_start=79
  _globals['_OBSERVATIONPROTO']._serialized_end=275
  _globals['_OBSERVATIONPROTO_FLOATDATA']._serialized_start=230
  _globals['_OBSERVATIONPROTO_FLOATDATA']._serialized_end=255
# @@protoc_insertion_point(module_scope)
