# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ueagents_envs/communicator_objects/unreal_output.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ueagents_envs.communicator_objects import unreal_rl_output_pb2 as ueagents__envs_dot_communicator__objects_dot_unreal__rl__output__pb2
from ueagents_envs.communicator_objects import unreal_rl_initialization_output_pb2 as ueagents__envs_dot_communicator__objects_dot_unreal__rl__initialization__output__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6ueagents_envs/communicator_objects/unreal_output.proto\x12\x14\x63ommunicator_objects\x1a\x39ueagents_envs/communicator_objects/unreal_rl_output.proto\x1aHueagents_envs/communicator_objects/unreal_rl_initialization_output.proto\"\xac\x01\n\x11UnrealOutputProto\x12<\n\trl_output\x18\x01 \x01(\x0b\x32).communicator_objects.UnrealRLOutputProto\x12Y\n\x18rl_initialization_output\x18\x02 \x01(\x0b\x32\x37.communicator_objects.UnrealRLInitializationOutputProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ueagents_envs.communicator_objects.unreal_output_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_UNREALOUTPUTPROTO']._serialized_start=214
  _globals['_UNREALOUTPUTPROTO']._serialized_end=386
# @@protoc_insertion_point(module_scope)
