# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ueagents_envs/communicator_objects/unreal_rl_initialization_output.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ueagents_envs.communicator_objects import brain_parameters_pb2 as ueagents__envs_dot_communicator__objects_dot_brain__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHueagents_envs/communicator_objects/unreal_rl_initialization_output.proto\x12\x14\x63ommunicator_objects\x1a\x39ueagents_envs/communicator_objects/brain_parameters.proto\"\xc1\x01\n!UnrealRLInitializationOutputProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x15\x63ommunication_version\x18\x02 \x01(\t\x12\x10\n\x08log_path\x18\x03 \x01(\t\x12\x44\n\x10\x62rain_parameters\x18\x04 \x03(\x0b\x32*.communicator_objects.BrainParametersProto\x12\x17\n\x0fpackage_version\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ueagents_envs.communicator_objects.unreal_rl_initialization_output_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_UNREALRLINITIALIZATIONOUTPUTPROTO']._serialized_start=158
  _globals['_UNREALRLINITIALIZATIONOUTPUTPROTO']._serialized_end=351
# @@protoc_insertion_point(module_scope)
