# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ueagents_envs/communicator_objects/unreal_input.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ueagents_envs.communicator_objects import unreal_rl_input_pb2 as ueagents__envs_dot_communicator__objects_dot_unreal__rl__input__pb2
from ueagents_envs.communicator_objects import unreal_rl_initialization_input_pb2 as ueagents__envs_dot_communicator__objects_dot_unreal__rl__initialization__input__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5ueagents_envs/communicator_objects/unreal_input.proto\x12\x14\x63ommunicator_objects\x1a\x38ueagents_envs/communicator_objects/unreal_rl_input.proto\x1aGueagents_envs/communicator_objects/unreal_rl_initialization_input.proto\"\xa7\x01\n\x10UnrealInputProto\x12:\n\x08rl_input\x18\x01 \x01(\x0b\x32(.communicator_objects.UnrealRLInputProto\x12W\n\x17rl_initialization_input\x18\x02 \x01(\x0b\x32\x36.communicator_objects.UnrealRLInitializationInputProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ueagents_envs.communicator_objects.unreal_input_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_UNREALINPUTPROTO']._serialized_start=211
  _globals['_UNREALINPUTPROTO']._serialized_end=378
# @@protoc_insertion_point(module_scope)
